namespace OnefinityProbeAutoCalibration.Models
{
    public class MachineState
    {
        public bool imperial { get; set; }
        public int _2ic { get; set; }
        public float max_arc_error { get; set; }
        public int _2sp { get; set; }
        public int jvr { get; set; }
        public int _9vt { get; set; }
        public float _if { get; set; }
        public bool load2_shutdown { get; set; }
        public float _0zb { get; set; }
        public int _6va { get; set; }
        public string[] files { get; set; }
        public float _3sa { get; set; }
        public int sc { get; set; }
        public int _2mi { get; set; }
        public int _0xw { get; set; }
        public int _3tr { get; set; }
        public int _3xw { get; set; }
        public int pvt { get; set; }
        public int evv { get; set; }
        public int cva { get; set; }
        public float vin { get; set; }
        public float _3sv { get; set; }
        public int a_min { get; set; }
        public int jva { get; set; }
        public int nvr { get; set; }
        public int avv { get; set; }
        public decimal offset_a { get; set; }
        public int gvr { get; set; }
        public decimal tool { get; set; }
        public int _0xs { get; set; }
        public int _2vv { get; set; }
        public int rvv { get; set; }
        public int _2xs { get; set; }
        public int et { get; set; }
        public int _2lw { get; set; }
        public decimal dt { get; set; }
        public int _3tn { get; set; }
        public int _1om { get; set; }
        public int _2tm { get; set; }
        public int dos { get; set; }
        public int ma { get; set; }
        public int _4vr { get; set; }
        public int _1lb { get; set; }
        public decimal xp { get; set; }
        public float _0tv { get; set; }
        public int _3vm { get; set; }
        public int _9vv { get; set; }
        public string hid { get; set; }
        public int _1tm { get; set; }
        public int _2os { get; set; }
        public int _2ls { get; set; }
        public int rvt { get; set; }
        public int _9va { get; set; }
        public bool eoa { get; set; }
        public int _1vv { get; set; }
        public int _2am { get; set; }
        public int tos { get; set; }
        public int _1ho { get; set; }
        public float _0dc { get; set; }
        public int _0vm { get; set; }
        public bool load1_shutdown { get; set; }
        public int _1vm { get; set; }
        public int _1tc { get; set; }
        public int _3df { get; set; }
        public int dvv { get; set; }
        public int _1am { get; set; }
        public int pwr_version { get; set; }
        public int _3ic { get; set; }
        public bool over_voltage { get; set; }
        public bool shunt_error { get; set; }
        public int _3va { get; set; }
        public int _3mi { get; set; }
        public int _2lb { get; set; }
        public int qva { get; set; }
        public int _3sp { get; set; }
        public int c_min { get; set; }
        public int _1os { get; set; }
        public float _0max { get; set; }
        public bool motor_overload { get; set; }
        public float vdd { get; set; }
        public string er { get; set; }
        public float _1tv { get; set; }
        public int bvt { get; set; }
        public float _3dc { get; set; }
        public bool metric { get; set; }
        public int ivv { get; set; }
        public int gvv { get; set; }
        public int svr { get; set; }
        public int mb { get; set; }
        public int _2vm { get; set; }
        public bool _3h { get; set; }
        public int _2xw { get; set; }
        public int fo { get; set; }
        public bool load1_sense_error { get; set; }
        public int line { get; set; }
        public int rpi_temp { get; set; }
        public int _3am { get; set; }
        public int _3vr { get; set; }
        public int _0an { get; set; }
        public decimal offset_x { get; set; }
        public int _1ls { get; set; }
        public int _9vr { get; set; }
        public int pw { get; set; }
        public int _1tn { get; set; }
        public int _1xs { get; set; }
        public int _3lw { get; set; }
        public int _8va { get; set; }
        public int gvt { get; set; }
        public int hvt { get; set; }
        public bool _2homed { get; set; }
        public int sx { get; set; }
        public int tvr { get; set; }
        public int _8vv { get; set; }
        public int _0tn { get; set; }
        public float _1dc { get; set; }
        public int qvr { get; set; }
        public int svv { get; set; }
        public bool over_current { get; set; }
        public bool _0me { get; set; }
        public int cp { get; set; }
        public bool doa { get; set; }
        public float _0lv { get; set; }
        public decimal offset_c { get; set; }
        public int _1df { get; set; }
        public int _5vr { get; set; }
        public int mvr { get; set; }
        public bool toa { get; set; }
        public bool _1h { get; set; }
        public int _8vt { get; set; }
        public int _3vv { get; set; }
        public int fvt { get; set; }
        public bool _2oa { get; set; }
        public int mva { get; set; }
        public int lva { get; set; }
        public int bp { get; set; }
        public int evt { get; set; }
        public int evr { get; set; }
        public int cvv { get; set; }
        public int _0jm { get; set; }
        public float load1 { get; set; }
        public int _0vv { get; set; }
        public int cvr { get; set; }
        public float _2sv { get; set; }
        public int st { get; set; }
        public int _0tr { get; set; }
        public decimal offset_b { get; set; }
        public float _1zb { get; set; }
        public int a_max { get; set; }
        public int fvr { get; set; }
        public bool _1oa { get; set; }
        public int _0tm { get; set; }
        public int ova { get; set; }
        public bool pi { get; set; }
        public string cycle { get; set; }
        public int eos { get; set; }
        public int _1mi { get; set; }
        public int _6vt { get; set; }
        public decimal yp { get; set; }
        public int dvr { get; set; }
        public int b_min { get; set; }
        public int _4vv { get; set; }
        public float feed { get; set; }
        public int _3an { get; set; }
        public int hvv { get; set; }
        public bool load2_sense_error { get; set; }
        public int hx { get; set; }
        public int bva { get; set; }
        public int mvv { get; set; }
        public int lvt { get; set; }
        public int nvv { get; set; }
        public int _2tr { get; set; }
        public int _0df { get; set; }
        public float _0sv { get; set; }
        public int ivr { get; set; }
        public bool mw { get; set; }
        public int kvr { get; set; }
        public bool hb { get; set; }
        public float bitDiameter { get; set; }
        public int qvt { get; set; }
        public float vout { get; set; }
        public int bvv { get; set; }
        public string pr { get; set; }
        public int _3ls { get; set; }
        public int _2df { get; set; }
        public int _2vt { get; set; }
        public int fva { get; set; }
        public int uvr { get; set; }
        public int cvt { get; set; }
        public int uvv { get; set; }
        public int _5vt { get; set; }
        public int pt { get; set; }
        public int hvr { get; set; }
        public float _3max { get; set; }
        public int ivt { get; set; }
        public decimal offset_y { get; set; }
        public int dvt { get; set; }
        public int _0sp { get; set; }
        public int _1an { get; set; }
        public bool _3me { get; set; }
        public int _0am { get; set; }
        public int _7vr { get; set; }
        public int _3jm { get; set; }
        public bool _1me { get; set; }
        public int _0mi { get; set; }
        public int _1jm { get; set; }
        public int _0va { get; set; }
        public int _0ls { get; set; }
        public int pwr_flags { get; set; }
        public int _3zb { get; set; }
        public bool sense_error { get; set; }
        public int _7vt { get; set; }
        public int _1vr { get; set; }
        public int _0lb { get; set; }
        public OnefinityMessage[] messages { get; set; }
        public string s { get; set; }
        public int _8vr { get; set; }
        public bool _2me { get; set; }
        public int plan_time { get; set; }
        public int _2va { get; set; }
        public int _2an { get; set; }
        public int so { get; set; }
        public float _2dc { get; set; }
        public int cr { get; set; }
        public bool motor_current_sense_error { get; set; }
        public int c_max { get; set; }
        public float _1sa { get; set; }
        public int ava { get; set; }
        public string selected { get; set; }
        public int ovt { get; set; }
        public int pvv { get; set; }
        public int hm { get; set; }
        public float _1max { get; set; }
        public int vf { get; set; }
        public int _1vt { get; set; }
        public int _1tr { get; set; }
        public float _3min { get; set; }
        public int uva { get; set; }
        public int pvr { get; set; }
        public int _2ho { get; set; }
        public int vvt { get; set; }
        public bool demo { get; set; }
        public int _1ic { get; set; }
        public float _0home { get; set; }
        public bool sr { get; set; }
        public int _1lm { get; set; }
        public int fos { get; set; }
        public float load2 { get; set; }
        public int _2tc { get; set; }
        public int _3ho { get; set; }
        public float _1min { get; set; }
        public int kva { get; set; }
        public float _2lv { get; set; }
        public int avr { get; set; }
        public bool _2h { get; set; }
        public int eva { get; set; }
        public int _0vr { get; set; }
        public int _4va { get; set; }
        public int _2om { get; set; }
        public float _1home { get; set; }
        public int ovr { get; set; }
        public int lvr { get; set; }
        public bool under_voltage { get; set; }
        public bool fa { get; set; }
        public int _2vr { get; set; }
        public int _0ic { get; set; }
        public int dva { get; set; }
        public int _0vt { get; set; }
        public int lvv { get; set; }
        public int fvv { get; set; }
        public int nvt { get; set; }
        public int b_max { get; set; }
        public bool _0rv { get; set; }
        public int sva { get; set; }
        public int uvt { get; set; }
        public int hq { get; set; }
        public decimal zp { get; set; }
        public float _1lv { get; set; }
        public int ss { get; set; }
        public int _1sp { get; set; }
        public int eom { get; set; }
        public int _3vt { get; set; }
        public int sd { get; set; }
        public int _6vr { get; set; }
        public int bvr { get; set; }
        public bool vdd_current_sense_error { get; set; }
        public int tvt { get; set; }
        public int _3xs { get; set; }
        public int _7vv { get; set; }
        public int _3tm { get; set; }
        public int ew { get; set; }
        public int _0lw { get; set; }
        public int _2lm { get; set; }
        public int hi { get; set; }
        public bool dp { get; set; }
        public float _3home { get; set; }
        public float _3tv { get; set; }
        public int _4vt { get; set; }
        public float _2sa { get; set; }
        public bool motor_under_voltage { get; set; }
        public int tva { get; set; }
        public decimal ap { get; set; }
        public int _3lm { get; set; }
        public int _3lb { get; set; }
        public float _2tv { get; set; }
        public int _2jm { get; set; }
        public int _2tn { get; set; }
        public int temp { get; set; }
        public float _0min { get; set; }
        public int fom { get; set; }
        public int qvv { get; set; }
        public float _0sa { get; set; }
        public float _0homed { get; set; }
        public int _3tc { get; set; }
        public int kvv { get; set; }
        public bool _2rv { get; set; }
        public bool _3rv { get; set; }
        public int _6vv { get; set; }
        public int hva { get; set; }
        public float _2zb { get; set; }
        public float _1homed { get; set; }
        public int vva { get; set; }
        public int mvt { get; set; }
        public int gva { get; set; }
        public int ovv { get; set; }
        public decimal v { get; set; }
        public int avt { get; set; }
        public int tvv { get; set; }
        public delegate void StateUpdatedHandler(string oldState, string newState);
        public event StateUpdatedHandler StateUpdated;
        private string _xx { get; set; }
        public string xx
        {
            get
            {
                return _xx;
            }
            set
            {
                if (StateUpdated != null)
                {
                    StateUpdated(_xx, value);
                }

                _xx = value;
            }
        }

        public int mx { get; set; }
        public int jvt { get; set; }
        public float _3lv { get; set; }
        public int nd { get; set; }
        public bool es { get; set; }
        public bool foa { get; set; }
        public int _7va { get; set; }
        public int pva { get; set; }
        public int _5va { get; set; }
        public int xc { get; set; }
        public bool motor_voltage_sense_error { get; set; }
        public int svt { get; set; }
        public int _0ho { get; set; }
        public int rvr { get; set; }
        public float selected_time { get; set; }
        public int _1va { get; set; }
        public int jvv { get; set; }
        public bool _0h { get; set; }
        public int un { get; set; }
        public float motor { get; set; }
        public int _0tc { get; set; }
        public string sid { get; set; }
        public int _5vv { get; set; }
        public float pa { get; set; }
        public int _1xw { get; set; }
        public float _3homed { get; set; }
        public decimal pv { get; set; }
        public bool power_shutdown { get; set; }
        public decimal offset_z { get; set; }
        public decimal speed { get; set; }
        public int dom { get; set; }
        public bool _1rv { get; set; }
        public int nva { get; set; }
        public int vvr { get; set; }
        public int kvt { get; set; }
        public float md { get; set; }
        public int id { get; set; }
        public int rva { get; set; }
        public int _1lw { get; set; }
        public int tom { get; set; }
        public int iva { get; set; }
        public int _0lm { get; set; }
        public bool shunt_overload { get; set; }
        public int sm { get; set; }
        public float _1sv { get; set; }
        public int vvv { get; set; }
    }

    public class OnefinityMessage
    {
        public string id { get; set; }
        public string text { get; set; }
    }
}